colors_map_path: "data/graphene_maps/paper_map.json"

screen:
  width: 1280
  height: 720

passive_drill:
  stimulus_duration : 1 # 1
  background_color_duration : 0.5 # 0.5
  min_repeats : 3 # 3
  max_repeats : 10 # 10
  global_repeats : 2 # 2

early-dmts:
  stimulus_duration : 1.5 # 1.5s
  delay_duration : 3 # 3s
  response_duration : 4 # 4s
  feedback_duration : 1 # # original unknown, 1s
  initial_fake_similarity : 0.5 # original unknown, 0.5
  success_delta_similarity : 0.2 # 0.2
  failure_delta_similarity : -0.2 # -0.2
  total_trials : 30 # 30

span:
  initial_sequence_length : 6 # original unknown, 6
  stimulus_duration : 0.5 # 500ms
  gap_duration : 0.25 # 250ms
  response_delay : 0.5 # 500ms
  total_trials : 30 # 30

speed_test:
  gap_duration : 0.25 # 250ms
  show_feedback : false # originally - false
  total_trials : 3 # 100


# for late-dmts the parameters are the same